import type { ColumnConfig } from "@/framework/components/data-view/core/ui/createColumnsFromConfig";
import { Gender } from "@/app/types/main/Relation";

export const todoColumns: ColumnConfig[] = [
  { field: "id", label: { en: "Id", ro: "Id" }, type: "number", size: 55, cardHidden: true },
  { field: "title", label: { en: "Title", ro: "Titlu" }, type: "text", size: 300 },
  { field: "completed", label: { en: "Completed", ro: "Finalizat" }, type: "boolean", size: 90 },
  { field: "notes", label: { en: "Notes", ro: "Note" }, type: "text", size: 300 },
  {
    field: "user_id",
    label: { en: "User id", ro: "Id utilizator" },
    type: "number",
    size: 70,
    hidden: true,
  },
  {
    field: "relation_username",
    label: { en: "Username", ro: "Nume utilizator" },
    type: "text",
    size: 110,
    columnName: "username",
    origin: "relation",
    accessorFn: (row) => row.relation?.username,
    navigationHidden: true,
    cardNavigationHidden: true,
  },
  {
    field: "relation_first_name",
    label: { en: "First name", ro: "Prenume" },
    type: "text",
    size: 90,
    columnName: "first_name",
    origin: "relation",
    accessorFn: (row) => row.relation?.first_name,
    hidden: true,
  },
  {
    field: "relation_last_name",
    label: { en: "Last name", ro: "Nume" },
    type: "text",
    size: 90,
    columnName: "last_name",
    origin: "relation",
    accessorFn: (row) => row.relation?.last_name,
    hidden: true,
  },
  {
    field: "relation_email",
    label: { en: "Email", ro: "Email" },
    type: "text",
    size: 250,
    columnName: "email",
    origin: "relation",
    accessorFn: (row) => row.relation?.email,
    hidden: true,
  },
  {
    field: "relation_gender",
    label: { en: "Gender", ro: "Gen" },
    type: "select",
    size: 85,
    columnName: "gender",
    origin: "relation",
    accessorFn: (row) => row.relation?.gender,
    hidden: true,
    selectOptions: Gender.options,
  },
  {
    field: "created_at",
    label: { en: "Add time", ro: "Data adăugării" },
    type: "datetime",
    size: 130,
    hidden: true,
  },
];

export const todoPickupColumns: ColumnConfig[] = [
  { field: "id", label: { en: "Id", ro: "Id" }, type: "number", size: 70 },
  { field: "title", label: { en: "Title", ro: "Titlu" }, type: "text", size: 300 },
  { field: "completed", label: { en: "Completed", ro: "Finalizat" }, type: "boolean", size: 80 },
  { field: "notes", label: { en: "Notes", ro: "Note" }, type: "text", size: 300 },
  {
    field: "created_at",
    label: { en: "Created at", ro: "Data creării" },
    type: "datetime",
    size: 140,
  },
];
