import type { ColumnConfig } from "@/framework/components/data-view/core/ui/createColumnsFromConfig";
import { describeGrantResource, isGrantableAction } from "@/app/grantablePermissions";

export const rolePermissionColumns: ColumnConfig[] = [
  { field: "id", label: { en: "Id", ro: "Id" }, type: "number", size: 70, cardHidden: true },
  // Not shown — exists only so the roles→permissions relation tab can
  // pre-filter by it (see src/components/features/roles/config/relations.ts).
  {
    field: "role_id",
    label: { en: "Role Id", ro: "Id rol" },
    type: "number",
    hidden: true,
    cardHidden: true,
  },
  {
    field: "role_name",
    label: { en: "Role", ro: "Rol" },
    type: "text",
    size: 160,
    columnName: "name",
    origin: "role",
    hidden: true,
    cardHidden: true,
    accessorFn: (row) => row.role?.name,
  },
  {
    field: "resource_label",
    label: { en: "Resource", ro: "Resursă" },
    type: "text",
    size: 200,
    accessorFn: (row) => describeGrantResource(row.resource_id),
    cardGroup: "resource",
    cardGroupLabel: { en: "Resource", ro: "Resursă" },
  },
  {
    field: "resource_type",
    label: { en: "Type", ro: "Tip" },
    type: "text",
    size: 110,
    accessorFn: (row) =>
      isGrantableAction(row.resource_id) ? "action" : "resource",
    cardGroup: "resource",
  },
  {
    field: "can_read",
    label: { en: "Read", ro: "Citire" },
    type: "boolean",
    size: 90,
    cardGroup: "permissions",
    cardGroupLabel: { en: "Permissions", ro: "Permisiuni" },
    cardLabel: { en: "Read", ro: "Citire" },
    cardLabelPosition: "before",
  },
  {
    field: "can_add",
    label: { en: "Add", ro: "Adăugare" },
    type: "boolean",
    size: 90,
    cardGroup: "permissions",
    cardLabel: { en: "Add", ro: "Adăugare" },
    cardLabelPosition: "before",
  },
  {
    field: "can_update",
    label: { en: "Modify", ro: "Modificare" },
    type: "boolean",
    size: 90,
    cardGroup: "permissions",
    cardLabel: { en: "Modify", ro: "Modificare" },
    cardLabelPosition: "before",
  },
  {
    field: "can_delete",
    label: { en: "Delete", ro: "Ștergere" },
    type: "boolean",
    size: 90,
    cardGroup: "permissions",
    cardLabel: { en: "Delete", ro: "Ștergere" },
    cardLabelPosition: "before",
  },
  {
    field: "allowed",
    label: { en: "Allowed", ro: "Permis" },
    type: "boolean",
    size: 90,
    cardGroup: "permissions",
    cardLabel: { en: "Allowed", ro: "Permis" },
    cardLabelPosition: "before",
  },
];
