import type { ColumnConfig } from "@/framework/components/data-view/core/ui/createColumnsFromConfig";

export const rolePermissionColumns: ColumnConfig[] = [
  { field: "id", label: "Id", type: "number", size: 70, cardHidden: true },
  // Not shown — exists only so the roles→permissions relation tab can
  // pre-filter by it (see src/components/features/roles/config/relations.ts).
  {
    field: "role_id",
    label: "Role Id",
    type: "number",
    hidden: true,
    cardHidden: true,
  },
  {
    field: "role_name",
    label: "Role",
    type: "text",
    size: 160,
    columnName: "name",
    origin: "role",
    hidden: true,
    cardHidden: true,
    accessorFn: (row) => row.role?.name,
  },
  {
    field: "resource_name",
    label: "Resource",
    type: "text",
    size: 200,
    columnName: "name",
    origin: "resource",
    accessorFn: (row) => row.resource?.name,
    cardGroup: "resource",
    cardGroupLabel: "Resource",
  },
  {
    field: "resource_type",
    label: "Type",
    type: "text",
    size: 110,
    columnName: "type",
    origin: "resource",
    accessorFn: (row) => row.resource?.type,
    cardGroup: "resource",
  },
  {
    field: "can_read",
    label: "Read",
    type: "boolean",
    size: 90,
    cardGroup: "permissions",
    cardGroupLabel: "Permissions",
    cardLabel: "Read",
    cardLabelPosition: "before",
  },
  {
    field: "can_add",
    label: "Add",
    type: "boolean",
    size: 90,
    cardGroup: "permissions",
    cardLabel: "Add",
    cardLabelPosition: "before",
  },
  {
    field: "can_update",
    label: "Modify",
    type: "boolean",
    size: 90,
    cardGroup: "permissions",
    cardLabel: "Modify",
    cardLabelPosition: "before",
  },
  {
    field: "can_delete",
    label: "Delete",
    type: "boolean",
    size: 90,
    cardGroup: "permissions",
    cardLabel: "Delete",
    cardLabelPosition: "before",
  },
  {
    field: "allowed",
    label: "Allowed",
    type: "boolean",
    size: 90,
    cardGroup: "permissions",
    cardLabel: "Allowed",
    cardLabelPosition: "before",
  },
];
